# Generated by Django 4.2.6 on 2023-11-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_lang_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='lang_code',
            field=models.CharField(max_length=5),
        ),
    ]
