# Generated by Django 4.2.6 on 2023-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_channel_created_at_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='er',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='er24',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='lang_code',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='participants',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='views24',
            field=models.IntegerField(null=True),
        ),
    ]
