# Generated by Django 4.2.6 on 2023-11-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0008_alter_channel_er_alter_channel_er24_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
