# Generated by Django 4.2.6 on 2023-11-08 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0009_alter_advertisement_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='advertisements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ad_seller', to='channel.advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_seller', to='channel.channel'),
        ),
    ]
