# Generated by Django 4.2.6 on 2023-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0010_channel_advertisements_alter_advertisement_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_show',
            field=models.BooleanField(default=False),
        ),
    ]
