# Generated by Django 4.2.6 on 2023-11-13 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channel', '0011_category_is_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManagerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='channel.category')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_manager_history',
                'ordering': ['user', 'category', 'date'],
            },
        ),
    ]
