# Generated by Django 4.2.6 on 2023-11-11 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_permissions_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='Subscription Level')),
                ('description', models.TextField(verbose_name='Description')),
                ('ads_period_min', models.PositiveSmallIntegerField(verbose_name='Min ads period')),
                ('ads_period_max', models.PositiveSmallIntegerField(verbose_name='Max ads period')),
                ('managers_per_day', models.PositiveIntegerField(verbose_name='Managers per day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('is_active', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=50, verbose_name='Payment Status')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Payment Date')),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.subscription', verbose_name='Subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
    ]
