# Generated by Django 4.2.6 on 2023-11-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_payment_table_alter_subscription_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.payment'),
        ),
    ]
