# Generated by Django 4.2.6 on 2023-11-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customuser_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.payment', verbose_name='user'),
        ),
    ]
